{
  pkgs,
  self,
  lib,
  system,
  inputs,
  config,
  ...
}:
{
  home.packages = lib.mkIf config.gui.hyprland.enable (
    with pkgs;
    [
      libadwaita
      adwaita-icon-theme
      bc
      bibata-cursors
      brightnessctl
      cava
      cpufrequtils
      fuzzel
      glib
      gnome-system-monitor
      grim
      gsettings-qt
      gtk-engine-murrine
      gtk4
      gtk3
      dconf
      hypridle
      hyprland
      hyprland-qtutils
      hyprland-qt-support
      hyprland-protocols
      hyprlock
      hyprpicker
      hyprshade
      hyprsunset
      inxi
      libappindicator
      polkit_gnome
      rofi-wayland
      slurp
      swappy
      swaynotificationcenter
      swww
      wallust
      waybar
      waypaper
      wlogout
    ]
  );
}
