{ config, username, ... }: let
  cfg = config.server;
  fqdn = cfg.domain;

  webuiPort = 8088;
in {
  services.qbittorrent = {
    torrentingPort = 45372;
    inherit webuiPort;
    profileDir = "${config.server.configPath}/qbittorrent";

    serverConfig = {
      LegalNotice.Accepted = true;
      Preferences = {
        WebUI = {
          Username = username;
          Password_PBKDF2 = "generated ByteArray.";
        };
        General.Locale = "en";
      };
    }
    ;
  };

  services.caddy.virtualHosts."qbittorrent.${fqdn}" = {
    extraConfig = ''
      reverse_proxy http://localhost:${toString webuiPort}
    '';
  };
}
